openapi: "3.0.0"
info:
 title: TODO API
 version: "0.0.1"
 description: TODO API
tags:
 - name: opts
   description: 運用監視関連のAPI
 - name: tasks
   description: タスク関連のAPI
paths:
 /health:
   get:
    tags:
    - opts
    responses:
     '200':
       description: OK
 /tasks/:
  post:
   summary: "タスク作成"
   description: "タスク新規作成します。"
   operationId: createTask
   tags:
    - tasks
   responses:
     '201':
      description: created
 /tasks/{taskId}:
   get: 
    tags:
    - tasks
    summary: "タスク取得"
    operationId: showTask
    parameters:
    - name: taskId
      in: path
      required: true
      description: "詳細を取得するタスク"
      schema: 
       type: integer
       format: int64
    responses:
     '200':
      description: OK
      content:
       application/json:
        schema:
         $ref: "#/components/schemas/TaskDTO"
     '400':
      description: Not Found
      content:
       application/json:
        schema:
         $ref: "#/components/schemas/ResourseNotFoundError"
components:
 schemas:
  TaskDTO:
   type: object
   properties:
     id:
       type: integer
       format: int64
       description: "Task ID"
     title:
       type: string
       description: "Task Title"
   required:
   - id
   - title
  ResourseNotFoundError:
   description: "指定したリソースが存在しません。"
   type: object
   properties:
     title:
       type: string
       description: "Error title"
       default: "Resource Not Found"
     detail:
       type: string
       description: "Error Detail"
   required:
    - title
    - detail 
   
     
    